### PR TITLE
Missing changes from Bitbucket

### PR DESCRIPTION
**Pull request by rschmied**
- added requests-toolbelt (missing dependency),
  resolves https://github.com/CiscoDevNet/virl2-client/issues/10
- also added pytest configuration files
- added fixtures for tests to pass
- added tests which were missing from Bitbucket
- applied black formatting
- GitHub test automation
- assure 3.5 compatibility
- remove hashes from requirements.txt

### CODE REVIEW

**Review by rschmied — COMMENTED** [review]
need to add @xorrkaz as a reviewer

**Comment by xorrkaz** [comment]
Looks good to me.  Could we also add 3.9 to the supported Python list?

**Review by xorrkaz — APPROVED** [review]
Thanks for the Python add.

**Comment by xorrkaz** [comment]
Why pull out Python 3.9 now?

**Comment by rschmied** [comment]
I've merged this now -- I'm still not sure why the "action workflows" fail even though they do pass locally. Maybe it's a resource issue (e.g. running out of minutes or something).  I wish there would be better indication of why things get cancelled instead of simply cancelling all workflows with no obvious reason.

**Pull request merged**
